version: '2'

services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - 5000:5432
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
  db2:
    image: 'mongo:3.2.4'
    container_name: db2
    ports:
      - 27017:27017
